name: Python CI

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.tx
    - name: Run tests
      run: |
        python -m unittest
    -name: Lint with Flake8
      run: |
        pip install flake8
        # Stop workflow if find style issues
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit with 0 iff no issue found
        flake8 . --count -- exit-zero --max-complexity=10 --max-line-length=127
